version: '3.6'

networks:
  seidor-network:
    driver: bridge

services:
  seidor-api:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: seidor-api
    environment:
      - MONGO_HOST=seidor-mongo
    ports:
      - 3333:3333
    depends_on:
      - seidor-mongo
    networks:
      - seidor-network
    links:
      - seidor-mongo

  seidor-mongo:
    image: bitnami/mongodb:latest
    container_name: seidor-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DB}
    volumes:
      - seidor-mongo-data:/bitnami
    ports:
      - 27017:27017
    networks:
      - seidor-network

volumes:
  seidor-mongo-data:
    driver: local
