version: '3.6'

networks:
  challenge-network:
    driver: bridge

services:
  seidor-challenge:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: seidor-challenge
    environment:
      - MONGO_HOST=challenge-mongo
    ports:
      - 3333:3333
    depends_on:
      - challenge-mongo
    networks:
      - challenge-network
    links:
      - challenge-mongo

  challenge-mongo:
    image: bitnami/mongodb:latest
    container_name: challenge-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DB}
    volumes:
      - challenge-mongo-data:/bitnami
    ports:
      - 27017:27017
    networks:
      - challenge-network

volumes:
  challenge-mongo-data:
    driver: local
